name: Update Rekomendasi CSV

on:
  repository_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Langkah 1: Checkout repositori menggunakan token rahasia
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      # Langkah 2: Ambil data CSV
      - name: Fetch Google Sheet TXT
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRhyB_qD4IIn4x3oU0KMtoSKidNEDHAS9XBhKiKd9fzZfYcll_5tjy8INRrmmXDtv30_j0peLmRKHXc/pub?gid=1100848518&single=true&output=csv" -o rekomendasi.txt

      # Langkah 3: Konfigurasi Git
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      # Langkah 4: Commit dan Push
      - name: Commit and Push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add rekomendasi.txt
            git commit -m "Update rekomendasi.txt with latest data"
            git push
          else
            echo "No changes to commit."
          fi
